"""add friends

Revision ID: 628e5c3530cb
Revises: be06dbce0344
Create Date: 2025-06-05 19:32:53.974291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628e5c3530cb'
down_revision = 'be06dbce0344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('fillowed_id', sa.Integer(), nullable=False),
    sa.Column('time_followed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fillowed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'fillowed_id')
    )
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name=op.f('friends_friend_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('friends_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'friend_id', name=op.f('friends_pkey'))
    )
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
