"""Fix review structur11e

Revision ID: 7c1b577123ff
Revises: 02f72eedc2f4
Create Date: 2025-06-03 03:41:16.279792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1b577123ff'
down_revision = '02f72eedc2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('review_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('review_movie_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('review_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'movie_id', name=op.f('review_pkey'))
    )
    # ### end Alembic commands ###
