"""user update

Revision ID: 8c2165546eee
Revises: 07697c802316
Create Date: 2025-06-07 17:09:20.275907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c2165546eee'
down_revision = '07697c802316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_name_ru', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('director_name_en', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('director_poster_url', sa.String(length=512), nullable=True))
        batch_op.alter_column('countries',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('genres',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.drop_column('director')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('genres',
               existing_type=sa.String(length=256),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('countries',
               existing_type=sa.String(length=256),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('director_poster_url')
        batch_op.drop_column('director_name_en')
        batch_op.drop_column('director_name_ru')

    # ### end Alembic commands ###
